### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by mogarg** [scheduler-tools/rt-app#10]
System information:  Ubuntu 14.04.4 LTS (GNU/Linux 3.18.31 x86_64)

$ sudo rt-app -t 10000:1000:d -D10
[rt-app] <notice> [0] Using SCHED_DEADLINE policy:
# Policy : SCHED_DEADLINE

[rt-app] <notice> [0] Locking pages in memory
# idx    period  min_et  max_et  rel_st  start       end     deadline    dur.    slack   Budget  Used Budget

[rt-app] <notice> [0] starting thread with period: 10000, exec: 1050,deadline: 10000, priority: 0
[rt-app] <notice> [0] Exiting.

**Comment by credp** [comment]
-t isn't supported now, and this is almost 3 years old. If anyone is still suffering from no output problems, please shout...
