### ISSUE TITLE
duty cycle issue

### ISSUE THREAD

**Issue by cloverpop** [scheduler-tools/rt-app#11]
Hi,

I define a 50% duty cycle workload and trigger rt-app to execute it. The output log of lowest CPU frequency is as below:
# Policy : SCHED_OTHER priority : 0
# idx     perf      run   period           start             end          rel_st      slack      c_run   c_period     wu_lat

   0  1449275   507272   507311      3065362105      3065869416            7960    -108415     200000     400000          0
   0  1449275   509090   509127      3065869445      3066378573          515301    -217572     200000     400000          0
   0  1449275   506842   506879      3066378600      3066885479         1024456    -324478     200000     400000          0

The problem is c_run is 200 ms (200000 ns) and period is 400 ms as what we defined.
But why actually "run" time is 507272 ns and "period" is 507311 ns?
In my tests, when CPU runs in higher frequency, "run" time and "period" time will be close to 200 ms / 400 ms; but in lower CPU frequency, "run" time and "period" time  are larger than 200ms / 400 ms.

Would you like to explain why this happen?

Thanks.

**Comment by vingu-linaro** [comment]
The behavior seems to be correct. run emulates the execution of a load. The duration is defined in
usec but the run event will effectively run a number of time a loop that waste cpu cycles. When the run event is executed, the duration is transformed in a number of loop thanks to the ns per loop value (see calibration). This way of working enables to emulate a load with a duration that will vary with the
frequency or the compute capacity of the CPU.
If you want a run that is platform and frequency invariant, you should use runtime event which runs for the specified amount of time irrespective of the compute capacity of the CPU of the frequency
