### ISSUE TITLE
usage: rt-app <taskset.json>

### ISSUE THREAD

**Issue by mli-tian** [scheduler-tools/rt-app#130]
the problem occurs when I try to run rt-app

**Comment by mli-tian** [comment]
I try to run 'rt-app -t 100000:10000:d -t 150000:20000:f:10 -D5' but failed

**Comment by vingu-linaro** [comment]
You can't provide thread's description in command line for a while now. You must use a json file to describe your threads. something like the below:

{
	"tasks" : {
		"thread-A" : {
			"instance" : 1,
			"loop" : -1,
			"policy" : "SCHED_DEADLINE",
			"dl-period" : 100000,
			"dl-runtime" : 11000,
			"run" :   10000,
			"timer" : { "ref" : "unique", "period" : 100000, "mode" : "absolute" }
		},
		"thread-B" : {
			"instance" : 1,
			"loop" : -1,
			"policy" : "SCHED_FIFO",
			"priority" : 10,
			"run" :   20000,
			"timer" : { "ref" : "unique", "period" : 150000, "mode" : "absolute" }
		}
	},
	"global" : {
		"duration" : 5,
		"default_policy" : "SCHED_OTHER",
		"pi_enabled" : true,
		"lock_pages" : true,
		"log_size" : "disable"
	}
}

**Comment by mli-tian** [comment]
> You can't provide thread's description in command line for a while now. You must use a json file to describe your threads. something like the below:
> 
> ```
> {
> 	"tasks" : {
> 		"thread-A" : {
> 			"instance" : 1,
> 			"loop" : -1,
> 			"policy" : "SCHED_DEADLINE",
> 			"dl-period" : 100000,
> 			"dl-runtime" : 11000,
> 			"run" :   10000,
> 			"timer" : { "ref" : "unique", "period" : 100000, "mode" : "absolute" }
> 		},
> 		"thread-B" : {
> 			"instance" : 1,
> 			"loop" : -1,
> 			"policy" : "SCHED_FIFO",
> 			"priority" : 10,
> 			"run" :   20000,
> 			"timer" : { "ref" : "unique", "period" : 150000, "mode" : "absolute" }
> 		}
> 	},
> 	"global" : {
> 		"duration" : 5,
> 		"default_policy" : "SCHED_OTHER",
> 		"pi_enabled" : true,
> 		"lock_pages" : true,
> 		"log_size" : "disable"
> 	}
> }
> ```

It  works！
Thank you very much for your answer!
