### ISSUE TITLE
Unhandled level 0 translation fault (11)

### ISSUE THREAD

**Issue by derkling** [scheduler-tools/rt-app#37]
Running an rt-app with the following configuration

```json
{
    "global": {
        "calibration": 262,
        "default_policy": "SCHED_OTHER",
        "duration": -1,
        "logdir": "/tmp"
    },
    "tasks": {
        "p20_400": {
            "cpus": [
                2
            ],
            "loop": 1,
            "phases": {
                "p000000": {
                    "delay": 350000
                },
                "p000001": {
                    "loop": 12,
                    "run": 80000,
                    "timer": {
                        "period": 400000,
                        "ref": "p20_400"
                    }
                }
            },
            "policy": "SCHED_OTHER"
        },
    }
}
```

generates a segfault at run-time.

According to the documentation, it seems that `delay` is not more supported as a `phase` attribute. However this error is not detected at JSON parsing time thus leading to an wired run-time error.

**Comment by jlelli** [comment]
Right. Moving "delay" at task level seems to solve the issue. Still we need to fix the bug.

**Comment by vingu-linaro** [comment]
I'm not able to reproduce the segfault. Have you tried the latest version ?
"delay" key is not parsed but only ignored when looking for event so not segfault  should happen

**Comment by vingu-linaro** [comment]
Hi,

As I'm not able to reproduce the problem with latest version of rt-app, I consider to close this issue.

Regards,
Vincent

**Comment by derkling** [comment]
Hi Vincent, I've just verified that with the current master, using the above agenda the app fails with:

```bash
$>./src/rt-app /tmp/test.json
[rt-app] <notice> pLoad = 262ns
[rt-app] <notice> [0] Locking pages in memory
mlockall: Cannot allocate memory
```

Did not investigated in details, but it seems to me that there are some issue with the JSON parsing.
AFAIU, for SCHED_OTHERS we should not mlockall memory pages... however, the app exit because of permission errors (notice that I'm not running as root this workload)

Thus, to me there is still a sudden bug in JSON processing... at least we fail on reporting an unexpected JSON entry.

**Comment by vingu-linaro** [comment]
1st, this seems to be a new "bug" as there is no segfault anymore.
Then, you need root permission for locking memory thus the error returns by rt-app but it's not the responsibility of rt-app just like you must be root to set sched_fifo
Finally, mlockall can be used with cfs task and it's even interesting because it prevent your test to be messed by some page fault.
I don't know why the doc mention non CFS task but there is no reason
So I don't see a bug in JSON processing here. At most, update of doc.

So in any case this should be filled in another bug because we are speaking about a different thing

**Comment by derkling** [comment]
Running as non root was intentional... but you right, I've just verified that we enforce mlockall by default also for SCHED_OTHER task. Then JSON parsing should be ok.
Let's close this for the time being. Thanks.
