### ISSUE TITLE
how to generate ftrace log with sched_switch event

### ISSUE THREAD

**Issue by aubreyli** [scheduler-tools/rt-app#41]
The log below looks very interesting, but I failed to find an example to generate this kind of log.
How to generate ftrace log with sched_switch event? Thanks!

         thread0-23345 [003] 115591.560884: tracing_mark_write: [0] starts
         thread0-23345 [003] 115591.560890: tracing_mark_write: [0] begins loop 0 phase 0 step 0
         thread0-23345 [003] 115591.560894: tracing_mark_write: [0] executing 0
         thread0-23345 [003] 115591.580212: tracing_mark_write: [0] executing 1
         thread0-23345 [003] 115591.580217: sched_switch: prev_comm=thread0 prev_pid=23345 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [003] 115591.670198: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=thread0 next_pid=23345 next_prio=120
         thread0-23345 [003] 115591.670243: tracing_mark_write: [0] end loop 0 phase 0 step 0
         thread0-23345 [003] 115591.670251: tracing_mark_write: [0] begins loop 0 phase 0 step 1
         thread0-23345 [003] 115591.670254: tracing_mark_write: [0] executing 0
         thread0-23345 [003] 115591.688081: tracing_mark_write: [0] executing 1
         thread0-23345 [003] 115591.688085: sched_switch: prev_comm=thread0 prev_pid=23345 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [003] 115591.778063: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=thread0 next_pid=23345 next_prio=120
         thread0-23345 [003] 115591.778108: tracing_mark_write: [0] end loop 0 phase 0 step 1
         thread0-23345 [003] 115591.778116: tracing_mark_write: [0] begins loop 0 phase 0 step 2
         thread0-23345 [003] 115591.778119: tracing_mark_write: [0] executing 0
         thread0-23345 [003] 115591.794619: tracing_mark_write: [0] executing 1
         thread0-23345 [003] 115591.794623: sched_switch: prev_comm=thread0 prev_pid=23345 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [003] 115591.884607: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=thread0 next_pid=23345 next_prio=120
         thread0-23345 [003] 115591.884652: tracing_mark_write: [0] end loop 0 phase 0 step 2

**Comment by vingu-linaro** [comment]
Hi,

Add in the "global" node the json file:
	"global" : {
...
		"ftrace" : true,
...
	},

This config will make rt-app inserting its trace events in the ftrace log.
Then you just have to record ftrace events with your favorite tool like trace-cmd

Regards,
Vincent

**Comment by aubreyli** [comment]
Oh, I thought I can add something like:
"ftrace" : {
        "event": {
                    "sched_switch",
         }
}

But anyway, I got what I want via trace-cmd on my side, thanks Vincent
=======================================================
 thread0-8166  [001] 137165.276571: print:                0xffffffff8115803es: [0] starts
         thread0-8166  [001] 137165.276605: print:                0xffffffff8115803es: [0] begins thread_loop 0 phase 0 phase_loop 0
         thread0-8166  [001] 137165.276607: print:                0xffffffff8115803es: [0] executing 0
         thread0-8166  [001] 137165.303343: print:                0xffffffff8115803es: [0] executing 1
         thread0-8166  [001] 137165.303346: sched_switch:         thread0:8166 [120] S ==> swapper/1:0 [120]
          <idle>-0     [001] 137165.383401: sched_switch:         swapper/1:0 [120] R ==> thread0:8166 [120]
         thread0-8166  [001] 137165.383415: print:                0xffffffff8115803es: [0] end thread_loop 0 phase 0 phase_loop 0
         thread0-8166  [001] 137165.383418: print:                0xffffffff8115803es: [0] begins thread_loop 0 phase 0 phase_loop 1
         thread0-8166  [001] 137165.383420: print:                0xffffffff8115803es: [0] executing 0
         thread0-8166  [001] 137165.407620: print:                0xffffffff8115803es: [0] executing 1
         thread0-8166  [001] 137165.407621: sched_switch:         thread0:8166 [120] S ==> swapper/1:0 [120]
          <idle>-0     [001] 137165.487676: sched_switch:         swapper/1:0 [120] R ==> thread0:8166 [120]
         thread0-8166  [001] 137165.487685: print:                0xffffffff8115803es: [0] end thread_loop 0 phase 0 phase_loop 1
         thread0-8166  [001] 137165.487688: print:                0xffffffff8115803es: [0] begins thread_loop 0 phase 0 phase_loop 2
         thread0-8166  [001] 137165.487689: print:                0xffffffff8115803es: [0] executing 0
         thread0-8166  [001] 137165.514148: print:                0xffffffff8115803es: [0] executing 1
         thread0-8166  [001] 137165.514150: sched_switch:         thread0:8166 [120] S ==> swapper/1:0 [120]
          <idle>-0     [001] 137165.594204: sched_switch:         swapper/1:0 [120] R ==> thread0:8166 [120]
