### ISSUE TITLE
the current version of json-c doesn't define 'TRUE' in json_object.h any longer.

### ISSUE THREAD

**Issue by v0lker** [scheduler-tools/rt-app#62]
actually since 
```
commit 0992aac61f8b087efd7094e9ac2b84fa9c040fcd
Author: Eric Haszlakiewicz <erh+git@nimenees.com>
Date:   Sat Dec 23 09:42:17 2017 -0500

    Remove the TRUE and FALSE defines.
```

could provide a PR but don't know which one you'd prefer:

would you rather like in `src/rt-app_parse_config.c`:
```
#ifndef TRUE
#include <json_object.h>
#define TRUE ((json_bool)1)
#define FALSE ((json_bool)0)
#endif
```

OR

```
#include <stdbool.h>
```
and rename all `TRUE`s to `true`

it is 2018, so we can assume C99 support and we can assume that JSON truth will be the same as the canonical one -?

OR

should it use `0` and `1` as the json-c people seem to intend ("Remove TRUE and FALSE defines, use 1 and 0 instead" 0992aac61f8b087efd7094e9ac2b84fa9c040fcd)

**Comment by jlelli** [comment]
Which repo/branch/version are you using?

**Comment by v0lker** [comment]
i was using the latest master of both rt-app and json-c, both from github (scheduler-tools/rt-app, json-c/json-c)

**Comment by jlelli** [comment]
Mmm. I'd say that it's safer/saner to use [latest release](https://github.com/json-c/json-c/releases/tag/json-c-0.13.1-20180305) of json-c which doesn't have this problem.
I'd propose we fix after (and if) json-c decides to make that move.
Maybe we should mention this in tutorial.txt though.. or maybe we could add json-c as a git submodule and enforce its version/head commit?

**Comment by v0lker** [comment]
somewhat related, shouldn't the tutorial's build section be split off into an INSTALL file?

it's not up to me to decide, but the submodule version sounds like a proper way of doing this. might prevent other issues from creeping up as well.

but: why is json-c treated magically? there are many projects that say they need `foo-dev` and people are normally happy to install the distro's package. there isn't really any requirement on a particular version of json-c in terms of functionality, or is there?

preemptively, the workaround (`#define TRUE 1`) seems still useful (because it's going to be someone else who's distro will be switching to a newer version of json-c), but maybe it's cleaner to `s/TRUE/true/g`?

**Comment by jlelli** [comment]
> somewhat related, shouldn't the tutorial's build section be split off into an INSTALL file?

We should indeed.

**Comment by jlelli** [comment]
> why is json-c treated magically?

Just because you might need to statically compile it for your sys/arch?

**Comment by jlelli** [comment]
> the workaround (`#define TRUE 1`) seems still useful

Guess it makes sense yes. Would you mind submitting a PR?

**Comment by v0lker** [comment]
i added a comment to the PR that pino-kim beat me to: https://github.com/scheduler-tools/rt-app/pull/63
but can also create another one. will also create one for INSTALL

**Comment by v0lker** [comment]
pino-kim/jlelli fixed it with https://github.com/scheduler-tools/rt-app/pull/65, works for me, thus closing.
